site_name: Abhay Gupta
site_url: https://blog.abgup.com

# plugins:
#  - optimize:
#      optimize_png_strip: false

theme:
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Tino
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  locale: en
  color_mode: auto
  user_color_mode_toggle: auto
  favicon: assets/a3.png
  logo: assets/a5.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - md_in_html # allow html in md
  - pymdownx.blocks.caption
  - admonition
  - attr_list # grids - https://squidfunk.github.io/mkdocs-material/reference/grids/
  - md_in_html # grids
  - pymdownx.highlight: # code syntax highlighting
      pygments_lang_class: true
  - pymdownx.superfences

extra:
  generator: false

extra_javascript: # table sorting built into mkdocs
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascript/tablesort.js

# rendering html in md
use_directory_urls: true
strict: false
